-- Insertar todas las ofertas laborales en la BD
USE red_egresados;

INSERT INTO ofertas_empleo (titulo, empresa, ubicacion, tipo, salario, descripcion, contacto, contacto_tipo, imagen_url, es_imagen, fijada) VALUES
('Jefe de Compras Internacionales (Bilingue)', 'Makei Soluciones', 'Barranquilla', 'Tiempo completo', 'A convenir', 'Rol estrategico liderando procesos de compras, importaciones y exportaciones.', 'talentohumano@makeisoluciones.com', 'email', 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=800', FALSE, FALSE),
('Perfilador Comercial', 'Sector Suministros Industriales', 'Medellin — Hibrido/Remoto', 'Termino indefinido', '$2.300.000 + variable $1.000.000', 'Identificacion de oportunidades comerciales en sector industrial y petroquimico.', 'reclutamiento.transformar@gmail.com', 'email', 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800', FALSE, FALSE),
('Gerente Comercial — Key Account Manager IT', 'Multinacional de Consultoria TI', 'Bogota', 'Tiempo completo', '$19.300.000 + beneficios + comisiones', 'Estrategia comercial en sector banca y servicios financieros.', 'luishurtado@talentop.com.co', 'email', 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=800', FALSE, FALSE),
('Administrador de Unidad Residencial', 'Propiedad Horizontal', 'Colombia', 'Termino indefinido', '$3.500.000', 'Gestion integral de conjunto residencial: administrativo, financiero y operativo.', 'gotalentoypersonas@gmail.com', 'email', 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800', FALSE, FALSE),
('Lider de Expansion — Franquicias', 'Polito', 'Medellin', 'Tiempo completo', 'A convenir', 'Impulsar el crecimiento de la red de franquicias a nivel nacional.', 'seleccion@polito.com.co', 'email', '/src/assets/images/oferta-polito.jpeg', TRUE, FALSE),
('Lider de Planeacion Logistica y Operaciones', 'Sector Construccion', 'Medellin', 'Termino indefinido', '$5.000.000 + variable', 'Planeacion de obra, control de proyectos, estimacion de materiales.', 'seleccionmariaclara@gmail.com', 'email', '/src/assets/images/oferta-logistica.jpeg', TRUE, FALSE),
('Coordinador Contable', 'Evaluarte', 'Medellin', 'Tiempo completo', '$4.825.000 — $5.403.000', 'Dirigir el area contable liderando la vision estrategica.', 'seleccion@evaluarteth.com', 'email', '/src/assets/images/oferta-contable.jpeg', TRUE, FALSE),
('Director(a) de Cuenta', 'Host Empresarial', 'Medellin — Bogota', 'Tiempo completo', 'A convenir', 'Manejo directo de clientes corporativos en agencias de publicidad.', 'hostemseleccion@gmail.com', 'email', '/src/assets/images/oferta-host.jpeg', TRUE, FALSE),
('Contador Publico', 'KIOS', 'Bogota', 'Tiempo completo', 'Competitivo + bonificaciones', 'Elaboracion y analisis de estados financieros, manejo de NIIF.', 'hojasdevidakios@gmail.com', 'email', '/src/assets/images/oferta-kios-contador.jpeg', TRUE, FALSE),
('Auxiliar Contable', 'KIOS', 'Bogota', 'Tiempo completo', 'Competitivo + bonificaciones', 'Registro de operaciones, causacion de facturas, conciliaciones bancarias.', 'hojasdevidakios@gmail.com', 'email', '/src/assets/images/oferta-kios-auxiliar.jpeg', TRUE, FALSE),
('Coordinadora Administrativa', 'Sandra Osorio — Talent Advisor', 'Medellin — Hibrida', 'Tiempo completo', '28.000 USD anuales', 'Gestion de proveedores, contratos, control presupuestario.', 'https://forms.gle/DDHDRynsTYU8q3RSA', 'link', '/src/assets/images/oferta-coordinadora.jpeg', TRUE, FALSE),
('Director de RRHH', 'Human One', 'La Estrella, Antioquia', 'Termino indefinido', '$5.000.000', 'Liderar areas de Gestion Humana en sector quimico/farmaceutico.', 'https://www.careers-page.com/human/job/63XYY49R', 'link', '/src/assets/images/oferta-rrhh.jpeg', TRUE, FALSE),
('Director de Desarrollo de Nuevos Negocios', 'Statera Consultores', 'Medellin — Hibrido', 'Tiempo completo', '$12.000.000 + comisiones', 'Desarrollo de oportunidades en industria de materias primas y pinturas.', 'vfranco@stateraconsultores.com.co', 'email', '/src/assets/images/oferta-statera.jpeg', TRUE, FALSE),
('Gerente de Operaciones', 'Expertia — Huevos y Escobas', 'Medellin', 'Termino indefinido', 'A convenir', 'Liderazgo de equipos, gestion de proyectos y optimizacion de procesos.', 'seleccion@expertiaconsultoria.com', 'email', '/src/assets/images/oferta-expertia.jpeg', TRUE, FALSE),
('Arquitecto de Soluciones Cloud PaaS', 'Evaluarte', 'Remoto', 'Tiempo completo', '$8.500.000', 'Disenar y desplegar infraestructuras Cloud en Azure y/o AWS.', 'seleccion@evaluarteth.com', 'email', '/src/assets/images/oferta-cloud.jpeg', TRUE, FALSE),
('Profesional Desarrollo Logistico', 'Casa Luker', 'Bogota', 'Tiempo completo', 'A convenir', 'Disenar, implementar y optimizar procesos de almacenamiento con SAP/ERP.', 'lcalderon@casaluker.com.co', 'email', '/src/assets/images/oferta-casaluker.jpeg', TRUE, FALSE),
('Director(a) Gestion Humana', 'Host Empresarial', 'Medellin', 'Tiempo completo', 'A convenir', 'Seleccion y atraccion del talento, bienestar laboral, cultura.', 'hostemseleccion@gmail.com', 'email', '/src/assets/images/oferta-gestion-humana.jpeg', TRUE, FALSE);
